# Generated by Django 2.2 on 2019-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200)),
                ('flavor', models.CharField(max_length=200)),
                ('extraBacon', models.BooleanField()),
                ('WithoutOnion', models.BooleanField()),
                ('StuffedEdge', models.BooleanField()),
            ],
            options={
                'db_table': 'pizza_order',
            },
        ),
    ]
