# Generated by Django 2.2 on 2019-04-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='StuffedEdge',
            new_name='stuffedEdge',
        ),
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='WithoutOnion',
            new_name='withoutOnion',
        ),
    ]
