FROM ubuntu:16.04
MAINTAINER Pedro Matias de Araújo (pedrom.araujo@outlook.com)

RUN apt-get -y update && apt-get -y upgrade

RUN apt-get install -y python3 \
    curl \
    python3-pip 

RUN pip3 install virtualenv \
    django \
    djangorestframework \
    model_mommy 


COPY . /portal
EXPOSE 8000
WORKDIR /portal

RUN python3 manage.py makemigrations 
RUN python3 manage.py migrate --run-syncdb 
